# Generated by Django 2.2.3 on 2019-09-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='ptroductitemimage',
            new_name='productitemimage',
        ),
    ]
