# Generated by Django 2.2.3 on 2019-09-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0002_auto_20190904_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='productitemname',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
