# Generated by Django 2.2.3 on 2019-09-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0003_auto_20190904_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='customerlatitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='customerlongitude',
            field=models.FloatField(),
        ),
    ]
