# Generated by Django 2.2.3 on 2019-09-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0004_auto_20190906_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='customeroder',
            field=models.CharField(max_length=250),
        ),
    ]
